import type { Creador, Encargo } from "./types";

export const CREADORES: Creador[] = [
  {
    id: "camila-barranco",
    nombre: "Camila Ríos",
    tiktok: "camcome.pe",
    ciudad: "Lima",
    nichos: ["Foodie", "Travel"],
    minPrecio: 320,
    seguidores: 4100,
    estilo: "Come en cámara, sin voz de comercial. Barranco y Miraflores.",
    whatsapp: "900000011",
    entregas: 3,
    redes: ["tiktok", "instagram"],
  },
  {
    id: "lucia-surco",
    nombre: "Lucía Mendoza",
    tiktok: "lu.skincare.pe",
    ciudad: "Lima",
    nichos: ["Belleza", "Maternidad"],
    minPrecio: 380,
    seguidores: 8200,
    estilo: "Reseñas de 20 segundos. Muestra textura, no pose.",
    whatsapp: "900000012",
    entregas: 2,
    redes: ["instagram", "tiktok"],
  },
  {
    id: "diego-gym",
    nombre: "Diego Palacios",
    tiktok: "diegomueve",
    ciudad: "Lima",
    nichos: ["Fitness"],
    minPrecio: 280,
    seguidores: 15600,
    estilo: "Rutinas cortas en gym de barrio. Habla como socio, no como coach.",
    whatsapp: "900000013",
    entregas: 1,
    redes: ["tiktok", "facebook"],
  },
  {
    id: "valeria-gamarra",
    nombre: "Valeria Quispe",
    tiktok: "vale.prueba",
    ciudad: "Lima",
    nichos: ["Moda", "Belleza"],
    minPrecio: 220,
    seguidores: 1900,
    estilo: "Prueba outfits de Gamarra. Precio en pantalla.",
    whatsapp: "900000014",
    entregas: 0,
  },
  {
    id: "andrea-arequipa",
    nombre: "Andrea Zuñiga",
    tiktok: "andreacomeaqp",
    ciudad: "Arequipa",
    nichos: ["Foodie"],
    minPrecio: 260,
    seguidores: 6700,
    estilo: "Platos arequipeños y delivery. Mejor retención que muchas limeñas.",
    whatsapp: "900000015",
    entregas: 2,
  },
  {
    id: "sofia-trujillo",
    nombre: "Sofía Alva",
    tiktok: "sofialva.ugc",
    ciudad: "Trujillo",
    nichos: ["Belleza", "Moda"],
    minPrecio: 240,
    seguidores: 3100,
    estilo: "Luz natural, un take. Cobra menos que Lima por el mismo corte.",
    whatsapp: "900000016",
    entregas: 1,
  },
  {
    id: "mateo-tech",
    nombre: "Mateo Hidalgo",
    tiktok: "hidalgo.unbox",
    ciudad: "Lima",
    nichos: ["Tecnología"],
    minPrecio: 400,
    seguidores: 12400,
    estilo: "Unbox de 15s. Dice el precio y si vale el Yape.",
    whatsapp: "900000017",
    entregas: 1,
  },
  {
    id: "pilar-mama",
    nombre: "Pilar Torres",
    tiktok: "pilarconlosdos",
    ciudad: "Lima",
    nichos: ["Maternidad", "Foodie"],
    minPrecio: 300,
    seguidores: 5400,
    estilo: "Casa real, hijos de fondo. Confianza de tía, no de set.",
    whatsapp: "900000018",
    entregas: 4,
  },
  {
    id: "renato-cusco",
    nombre: "Renato Huamán",
    tiktok: "renato.ruta",
    ciudad: "Cusco",
    nichos: ["Travel", "Foodie"],
    minPrecio: 350,
    seguidores: 9800,
    estilo: "Tours y comida callejera. Habla quechua y castellano.",
    whatsapp: "900000019",
    entregas: 2,
  },
  {
    id: "ines-piura",
    nombre: "Inés Calderón",
    tiktok: "ines.come.norte",
    ciudad: "Piura",
    nichos: ["Foodie"],
    minPrecio: 230,
    seguidores: 2700,
    estilo: "Ceviche, jugos, almuerzos. Audiencia norteña que sí pide.",
    whatsapp: "900000020",
    entregas: 0,
  },
  {
    id: "karla-miraflores",
    nombre: "Karla Benavides",
    tiktok: "karla.pruebaesto",
    ciudad: "Lima",
    nichos: ["Belleza", "Fitness"],
    minPrecio: 450,
    seguidores: 22100,
    estilo: "Antes/después sin filtro mentiroso. Pide derechos claros.",
    whatsapp: "900000021",
    entregas: 5,
  },
  {
    id: "thiago-dark",
    nombre: "Thiago León",
    tiktok: "thiagopedidos",
    ciudad: "Lima",
    nichos: ["Foodie"],
    minPrecio: 250,
    seguidores: 1300,
    estilo: "Graba el delivery como cliente. Ideal para dark kitchen.",
    whatsapp: "900000022",
    entregas: 0,
  },
];

export const ENCARGOS: Encargo[] = [
  {
    id: "ceviche-barranco",
    marca: "La Caleta Barranco",
    whatsapp: "900111001",
    nicho: "Foodie",
    ciudad: "Lima",
    videos: 5,
    precio: 380,
    plazo: "esta-semana",
    brief:
      "Cinco TikToks de platos del día. Comer en mesa, no voz de comercial. Derechos para pauta 30 días.",
    createdAt: "2026-09-11T15:00:00.000Z",
    redes: ["tiktok"],
  },
  {
    id: "serum-miraflores",
    marca: "Nube Skin",
    whatsapp: "900111002",
    nicho: "Belleza",
    ciudad: "Lima",
    videos: 3,
    precio: 450,
    plazo: "diez-dias",
    brief:
      "Tres reseñas del serum. Mostrar textura y rutina de noche. Enviamos el producto a Surco o Miraflores.",
    createdAt: "2026-09-10T18:20:00.000Z",
    redes: ["tiktok", "instagram"],
  },
  {
    id: "gym-surco",
    marca: "Hálito Gym",
    whatsapp: "900111003",
    nicho: "Fitness",
    ciudad: "Lima",
    videos: 4,
    precio: 320,
    plazo: "esta-semana",
    brief:
      "Cuatro clips de 15s en el local de Surco. Socio real, no modelo. Horario 7 a 9 am.",
    createdAt: "2026-09-12T08:10:00.000Z",
    redes: ["tiktok", "facebook"],
  },
  {
    id: "dark-san-miguel",
    marca: "Horno 12",
    whatsapp: "900111004",
    nicho: "Foodie",
    ciudad: "Lima",
    videos: 6,
    precio: 280,
    plazo: "esta-semana",
    brief:
      "Dark kitchen. Pedido por app, unbox en casa, primer bocado. Seis tomas, una por sabor.",
    createdAt: "2026-09-09T21:00:00.000Z",
  },
  {
    id: "cafe-arequipa",
    marca: "Tostadito Yanahuara",
    whatsapp: "900111005",
    nicho: "Foodie",
    ciudad: "Arequipa",
    videos: 3,
    precio: 300,
    plazo: "diez-dias",
    brief:
      "Tres videos del café de especialidad. Gente de Arequipa, no turista. Precio del vaso en pantalla.",
    createdAt: "2026-09-08T14:00:00.000Z",
  },
  {
    id: "ropa-gamarra",
    marca: "Taller 44",
    whatsapp: "900111006",
    nicho: "Moda",
    ciudad: "Lima",
    videos: 4,
    precio: 250,
    plazo: "esta-semana",
    brief:
      "Prueba 4 outfits de Gamarra. Decir talla y precio. Canje no: se paga el video.",
    createdAt: "2026-09-11T11:30:00.000Z",
    redes: ["instagram", "facebook"],
  },
  {
    id: "tour-cusco",
    marca: "Ruta Qosqo",
    whatsapp: "900111007",
    nicho: "Travel",
    ciudad: "Cusco",
    videos: 3,
    precio: 400,
    plazo: "diez-dias",
    brief:
      "Tres piezas de un city tour. Sin drone mentiroso. Gente local que ya camina el centro.",
    createdAt: "2026-09-07T16:45:00.000Z",
  },
];
